export const FLIGHTS = {
  LOAD: 'FLIGHTS_LOAD',
  LOAD_SUCCESS: 'FLIGHTS_LOAD_SUCCESS',
  LOAD_FAIL: 'FLIGHTS_LOAD_FAIL',
  ADD: 'FLIGHT_ADD',
  DELETE: 'FLIGHT_DELETE',
  UPDATE: 'FLIGHT_UPDATE',
};

export const SNACKBAR = {
  OPEN: 'SNACKBAR_OPEN',
  CLOSE: 'SNACKBAR_CLOSE',
};
